import menuImg1 from './images/food1.jpeg';
import menuImg2 from './images/food2.jpeg';
import menuImg3 from './images/food3.jpeg';
import menuImg4 from './images/food4.jpeg';
import menuImg5 from './images/food5.jpeg';
import menuImg6 from './images/food6.jpeg';
import topMenuImg from './images/cafe-img-2.jpeg';

export default function menuPage() {
    const bodyCont = document.createElement('div');
    const menuImgCont = document.createElement('div');
    const menuImg = document.createElement('img');
    const menuTitle = document.createElement('div');
    const menuCont = document.createElement('div');
    const foodItem1 = document.createElement('div');
    const foodItem2 = document.createElement('div');
    const foodItem3 = document.createElement('div');
    const foodItem4 = document.createElement('div');
    const foodItem5 = document.createElement('div');
    const foodItem6 = document.createElement('div');
    const foodImg1 = document.createElement('img');
    const foodImg2 = document.createElement('img');
    const foodImg3 = document.createElement('img');
    const foodImg4 = document.createElement('img');
    const foodImg5 = document.createElement('img');
    const foodImg6 = document.createElement('img');
    const food1Txt = document.createElement('div');
    const food2Txt = document.createElement('div');
    const food3Txt = document.createElement('div');
    const food4Txt = document.createElement('div');
    const food5Txt = document.createElement('div');
    const food6Txt = document.createElement('div');
    const food1Price = document.createElement('div');
    const food2Price = document.createElement('div');
    const food3Price = document.createElement('div');
    const food4Price = document.createElement('div');
    const food5Price = document.createElement('div');
    const food6Price = document.createElement('div');

    bodyCont.appendChild(menuImgCont);
    menuImgCont.appendChild(menuImg);
    menuImgCont.appendChild(menuTitle);
    bodyCont.appendChild(menuCont);
    menuCont.appendChild(foodItem1);
    menuCont.appendChild(foodItem2);
    menuCont.appendChild(foodItem3);
    menuCont.appendChild(foodItem4);
    menuCont.appendChild(foodItem5);
    menuCont.appendChild(foodItem6);
    foodItem1.appendChild(foodImg1);
    foodItem2.appendChild(foodImg2);
    foodItem3.appendChild(foodImg3);
    foodItem4.appendChild(foodImg4);
    foodItem5.appendChild(foodImg5);
    foodItem6.appendChild(foodImg6);
    foodItem1.appendChild(food1Txt);
    foodItem1.appendChild(food1Price);
    foodItem2.appendChild(food2Txt);
    foodItem2.appendChild(food2Price);
    foodItem3.appendChild(food3Txt);
    foodItem3.appendChild(food3Price);
    foodItem4.appendChild(food4Txt);
    foodItem4.appendChild(food4Price);
    foodItem5.appendChild(food5Txt);
    foodItem5.appendChild(food5Price);
    foodItem6.appendChild(food6Txt);
    foodItem6.appendChild(food6Price);

    menuTitle.innerHTML = 'Pastry';
    food1Txt.innerHTML = 'Taro Buttercream Bread';
    food1Price.innerHTML = '$12.95';
    food2Txt.innerHTML = 'Choco Cream Bread';
    food2Price.innerHTML = '$12.95';
    food3Txt.innerHTML = 'Honey Cheese Mochi Pancake';
    food3Price.innerHTML = '$12.95';
    food4Txt.innerHTML = 'Cream Cheese Stick Bread';
    food4Price.innerHTML = '$12.95';
    food5Txt.innerHTML = 'Garlic Cream Cheese Bread';
    food5Price.innerHTML = '$12.95';
    food6Txt.innerHTML = 'Red Bean Bread';
    food6Price.innerHTML = '$12.95';

    menuImg.src = topMenuImg;
    foodImg1.src = menuImg1;
    foodImg2.src = menuImg2;
    foodImg3.src = menuImg3;
    foodImg4.src = menuImg4;
    foodImg5.src = menuImg5;
    foodImg6.src = menuImg6;

    bodyCont.setAttribute('id', 'menu-body-cont');
    menuImgCont.setAttribute('id', 'menu-top-cont');
    menuImg.setAttribute('id', 'menu-top-img');
    menuTitle.setAttribute('id', 'menu-title');
    menuCont.setAttribute('id', 'menu-cont');
    foodItem1.classList.add('food-item');
    foodItem2.classList.add('food-item');
    foodItem3.classList.add('food-item');
    foodItem4.classList.add('food-item');
    foodItem5.classList.add('food-item');
    foodItem6.classList.add('food-item');
    foodImg1.classList.add('food-img');
    foodImg2.classList.add('food-img');
    foodImg3.classList.add('food-img');
    foodImg4.classList.add('food-img');
    foodImg5.classList.add('food-img');
    foodImg6.classList.add('food-img');
    food1Txt.classList.add('food-txt');
    food1Price.classList.add('food-price');
    food2Txt.classList.add('food-txt');
    food2Price.classList.add('food-price');
    food3Txt.classList.add('food-txt');
    food3Price.classList.add('food-price');
    food4Txt.classList.add('food-txt');
    food4Price.classList.add('food-price');
    food5Txt.classList.add('food-txt');
    food5Price.classList.add('food-price');
    food6Txt.classList.add('food-txt');
    food6Price.classList.add('food-price');

    return bodyCont;
}